Repository RevenueCat/purchases-flutter, pull requests merged in 2022-08, with the labels that each got.

#447 Update PHC to 4.1.4
  android/build.gradle
  ios/purchases_flutter.podspec
  macos/purchases_flutter.podspec
Labels: dependencies

#448 Release/4.2.0
  .version
  CHANGELOG-LATEST.md
  CHANGELOG.md
  VERSIONS.md
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  ios/Classes/PurchasesFlutterPlugin.m
  ios/purchases_flutter.podspec
  macos/purchases_flutter.podspec
  pubspec.yaml
  revenuecat_examples/MagicWeather/ios/Podfile.lock
  revenuecat_examples/purchase_tester/ios/Podfile.lock
  revenuecat_examples/purchase_tester/macos/Podfile.lock
Labels: next_release

#452 Configures Danger
  .circleci/config.yml
  Dangerfile
  Gemfile
  Gemfile.lock
Labels: ci

#454 Release train
  .circleci/config.yml
  Gemfile.lock
  fastlane/Fastfile
  fastlane/README.md
Labels: ci

#457 Add `next_version` and `automatic_release` to automatic_bump
  fastlane/Fastfile
Labels: ci

#458 Update RELEASING docs
  RELEASING.md
Labels: docs

#456 Update fastlane-plugin-revenuecat_internal
  Gemfile.lock
Labels: ci

#460 Skip release if needed and change type of message
  fastlane/Fastfile
Labels: ci

#462 Release/4.2.1
  .circleci/config.yml
  .version
  CHANGELOG-LATEST.md
  CHANGELOG.md
  RELEASING.md
  VERSIONS.md
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  ios/Classes/PurchasesFlutterPlugin.m
  ios/purchases_flutter.podspec
  macos/purchases_flutter.podspec
  pubspec.lock
  pubspec.yaml
  revenuecat_examples/MagicWeather/ios/Podfile.lock
  revenuecat_examples/purchase_tester/ios/Podfile.lock
  revenuecat_examples/purchase_tester/macos/Podfile.lock
Labels: next_release
