Repository RevenueCat/purchases-flutter, pull requests merged in 2023-03, with the labels that each got.

#632 Deprecate `usesStoreKit2IfAvailable`
  api_tester/lib/api_tests/models/purchase_configuration_api_test.dart
  lib/models/purchases_configuration.dart
  lib/purchases_flutter.dart
Labels: docs

#639 add `immediateAndChargeFullPrice` proration mode
  api_tester/lib/api_tests/purchases_flutter_api_test.dart
  lib/purchases_flutter.dart
Labels: feat

#612 Deprecate revenueCatId in favor of transactionIdentifier
  api_tester/lib/api_tests/models/store_transaction_api_test.dart
  lib/models/store_transaction.dart
  lib/models/store_transaction.freezed.dart
  lib/models/store_transaction.g.dart
  test/store_transaction_test.dart
Labels: refactor
