Repository RevenueCat/purchases-flutter, pull requests merged in 2023-06, with the labels that each got.

#703 Fix integration tests
  .circleci/config.yml
  android/build.gradle
  api_tester/android/build.gradle
  pubspec.yaml
  revenuecat_examples/MagicWeather/android/app/build.gradle
  revenuecat_examples/MagicWeather/android/app/proguard-rules.pro
  revenuecat_examples/MagicWeather/android/build.gradle
  revenuecat_examples/purchase_tester/android/app/build.gradle
  revenuecat_examples/purchase_tester/android/app/proguard-rules.pro
  revenuecat_examples/purchase_tester/android/build.gradle
Labels: build, ci

#706 Fix analyzer issues
  .circleci/config.yml
  analysis_options.yaml
  pubspec.yaml
  revenuecat_examples/MagicWeather/lib/store_config.dart
  revenuecat_examples/purchase_tester/integration_test/app_test.dart
  revenuecat_examples/purchase_tester/lib/src/app.dart
  revenuecat_examples/purchase_tester/lib/store_config.dart
  test/intro_eligibility_test.dart
  test/purchases_flutter_test.dart
Labels: build, ci

#708 [BC5] Add missing proration modes + fix analyzer issues
  api_tester/lib/api_tests/purchases_flutter_api_test.dart
  lib/google_product_change.dart
  revenuecat_examples/purchase_tester/lib/src/app.dart
Labels: feat

#716 Adding metadata to offering
  android/build.gradle
  api_tester/lib/api_tests/models/offering_wrapper_api_test.dart
  ios/purchases_flutter.podspec
  lib/models/offering_wrapper.dart
  lib/models/offering_wrapper.freezed.dart
  lib/models/offering_wrapper.g.dart
  macos/purchases_flutter.podspec
  test/offering_test.dart
Labels: feat

#719 Release/5.0.0-rc.1
  .version
  CHANGELOG-LATEST.md
  CHANGELOG.md
  VERSIONS.md
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  ios/Classes/PurchasesFlutterPlugin.m
  ios/purchases_flutter.podspec
  macos/purchases_flutter.podspec
  pubspec.yaml
Labels: next_release

#721 Add `isPrepaid` to `SubscriptionOffering`
  api_tester/lib/api_tests/models/subscription_option_wrapper_api_test.dart
  lib/models/subscription_option_wrapper.dart
  lib/models/subscription_option_wrapper.freezed.dart
  lib/models/subscription_option_wrapper.g.dart
  test/purchases_flutter_test.dart
Labels: feat

#724 Release/5.0.0
  .version
  CHANGELOG-LATEST.md
  CHANGELOG.md
  VERSIONS.md
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  ios/Classes/PurchasesFlutterPlugin.m
  ios/purchases_flutter.podspec
  macos/purchases_flutter.podspec
  pubspec.yaml
Labels: next_release

#722 Fix purchase tester reconfiguring the SDK
  revenuecat_examples/MagicWeather/lib/main.dart
  revenuecat_examples/MagicWeather/lib/src/views/home.dart
  revenuecat_examples/MagicWeather/lib/store_config.dart
  revenuecat_examples/purchase_tester/lib/main.dart
  revenuecat_examples/purchase_tester/lib/src/app.dart
  revenuecat_examples/purchase_tester/lib/store_config.dart
Labels: test

#729 [EXTERNAL] v5-MIGRATION.md: replace defaultOffer w/ defaultOption (#728)
  migrations/v5-MIGRATION.md
Labels: docs

#726 Fix flutter static analysis in pub.dev
  analysis_options.yaml
  api_tester/pubspec.yaml
  lib/models/customer_info_wrapper.dart
  lib/models/customer_info_wrapper.freezed.dart
  lib/models/entitlement_info_wrapper.dart
  lib/models/entitlement_info_wrapper.freezed.dart
  lib/models/entitlement_info_wrapper.g.dart
  lib/models/introductory_price.dart
  lib/models/introductory_price.freezed.dart
  lib/models/offering_wrapper.dart
  lib/models/offering_wrapper.freezed.dart
  lib/models/offerings_wrapper.dart
  lib/models/offerings_wrapper.freezed.dart
  lib/models/package_wrapper.dart
  lib/models/package_wrapper.freezed.dart
  lib/models/period_wrapper.dart
  lib/models/period_wrapper.freezed.dart
  lib/models/price_wrapper.dart
  lib/models/price_wrapper.freezed.dart
  lib/models/pricing_phase_wrapper.dart
  lib/models/pricing_phase_wrapper.freezed.dart
  lib/models/promotional_offer.dart
  lib/models/promotional_offer.freezed.dart
  lib/models/store_product_discount.dart
  lib/models/store_product_discount.freezed.dart
  lib/models/store_product_wrapper.dart
  lib/models/store_product_wrapper.freezed.dart
  lib/models/store_transaction.dart
  lib/models/store_transaction.freezed.dart
  lib/models/subscription_option_wrapper.dart
  lib/models/subscription_option_wrapper.freezed.dart
  lib/purchases_flutter.dart
  pubspec.yaml
  test/purchases_flutter_test.dart
Labels: refactor

#749 Adds package back to AndroidManifest.xml
  android/src/main/AndroidManifest.xml
Labels: fix
