Repository RevenueCat/purchases-flutter, pull requests merged in 2023-02, with the labels that each got.

#591 Added Purchases.setLogHandler
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  api_tester/lib/api_tests/purchases_flutter_api_test.dart
  ios/Classes/PurchasesFlutterPlugin.m
  lib/purchases_flutter.dart
  test/purchases_flutter_test.dart
Labels: feat

#599 Adds dependabot
  .github/dependabot.yml
  Gemfile
Labels: ci

#600 Sends PurchasesCustomerInfoUpdatedEvent and PurchasesReadyForPromotedProductPurchaseEvent on UiThread
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  ios/Classes/PurchasesFlutterPlugin.m
Labels: fix

#609 Add `syncObserverModeAmazonPurchase`
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  api_tester/lib/api_tests/purchases_flutter_api_test.dart
  ios/Classes/PurchasesFlutterPlugin.m
  lib/purchases_flutter.dart
  test/purchases_flutter_test.dart
Labels: feat

#610 fix(example): fix LogLevel debug enum
  revenuecat_examples/MagicWeather/lib/src/views/home.dart
Labels: docs

#621 Fixes NullPointerException at setUpdatedCustomerInfoListener
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
Labels: fix
