Repository RevenueCat/purchases-flutter, pull requests merged in 2023-05, with the labels that each got.

#694 Fix deprecation warning
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
Labels: fix

#700 Fix linter warnings using Flutter 3.10.2
  lib/models/customer_info_wrapper.dart
  lib/models/customer_info_wrapper.freezed.dart
  lib/models/entitlement_info_wrapper.dart
  lib/models/entitlement_info_wrapper.freezed.dart
  lib/models/offerings_wrapper.dart
  lib/models/offerings_wrapper.freezed.dart
  lib/models/store_product_wrapper.dart
  lib/models/store_product_wrapper.freezed.dart
  lib/purchases_flutter.dart
  pubspec.lock
  pubspec.yaml
Labels: fix

#701 Remove pubspec.lock
  .circleci/config.yml
  .gitignore
  pubspec.lock
Labels: build

#699 Fix issues when running Flutter 3.10.2
  .circleci/config.yml
  .gitignore
  lib/models/customer_info_wrapper.dart
  lib/models/customer_info_wrapper.freezed.dart
  lib/models/entitlement_info_wrapper.dart
  lib/models/entitlement_info_wrapper.freezed.dart
  lib/models/offerings_wrapper.dart
  lib/models/offerings_wrapper.freezed.dart
  lib/models/store_product_wrapper.dart
  lib/models/store_product_wrapper.freezed.dart
  lib/purchases_flutter.dart
  pubspec.lock
  pubspec.yaml
  revenuecat_examples/MagicWeather/android/build.gradle
  revenuecat_examples/MagicWeather/lib/src/app.dart
  revenuecat_examples/MagicWeather/lib/src/components/native_dialog.dart
  revenuecat_examples/MagicWeather/lib/src/components/top_bar.dart
  revenuecat_examples/MagicWeather/lib/src/model/weather_data.dart
  revenuecat_examples/MagicWeather/lib/src/views/home.dart
  revenuecat_examples/MagicWeather/lib/src/views/paywall.dart
  revenuecat_examples/MagicWeather/lib/src/views/user.dart
  revenuecat_examples/MagicWeather/lib/src/views/weather.dart
  revenuecat_examples/MagicWeather/lib/store_config.dart
  revenuecat_examples/MagicWeather/pubspec.yaml
  revenuecat_examples/purchase_tester/android/build.gradle
  revenuecat_examples/purchase_tester/ios/Runner.xcodeproj/project.pbxproj
  revenuecat_examples/purchase_tester/ios/Runner/Info.plist
  revenuecat_examples/purchase_tester/lib/src/app.dart
  revenuecat_examples/purchase_tester/lib/store_config.dart
  revenuecat_examples/purchase_tester/pubspec.yaml
Labels: ci

#702 Increases upper limit and removes minimum flutter version
  pubspec.yaml
Labels: dependencies

#698 Support Gradle 8+
  .circleci/config.yml
  .sdkmanrc
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  android/src/main/AndroidManifest.xml
  api_tester/android/app/build.gradle
  api_tester/android/app/src/debug/AndroidManifest.xml
  api_tester/android/app/src/main/AndroidManifest.xml
  api_tester/android/app/src/profile/AndroidManifest.xml
  api_tester/android/build.gradle
  api_tester/android/gradle.properties
  api_tester/android/gradle/wrapper/gradle-wrapper.properties
  revenuecat_examples/MagicWeather/android/app/build.gradle
  revenuecat_examples/MagicWeather/android/app/src/debug/AndroidManifest.xml
  revenuecat_examples/MagicWeather/android/app/src/main/AndroidManifest.xml
  revenuecat_examples/MagicWeather/android/app/src/profile/AndroidManifest.xml
  revenuecat_examples/MagicWeather/android/build.gradle
  revenuecat_examples/MagicWeather/android/gradle.properties
  revenuecat_examples/MagicWeather/android/gradle/wrapper/gradle-wrapper.properties
  revenuecat_examples/purchase_tester/android/app/build.gradle
  revenuecat_examples/purchase_tester/android/app/src/debug/AndroidManifest.xml
  revenuecat_examples/purchase_tester/android/app/src/main/AndroidManifest.xml
  revenuecat_examples/purchase_tester/android/app/src/profile/AndroidManifest.xml
  revenuecat_examples/purchase_tester/android/build.gradle
  revenuecat_examples/purchase_tester/android/gradle.properties
  revenuecat_examples/purchase_tester/android/gradle/wrapper/gradle-wrapper.properties
Labels: build
