Repository RevenueCat/purchases-flutter, pull requests merged in 2023-11, with the labels that each got.

#848 Remove unused GoogleProrationMode import
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
Labels: refactor

#857 Fix iOS integration tests for version 3.10.1
  .circleci/config.yml
Labels: test

#858 Add `3.10.1` to `VERSIONS`
  VERSIONS.md
Labels: docs

#861 Remove `.common_version`
  .common_version
Labels: refactor

#860 `Purchase Tester`: remove unused `Activity`
  revenuecat_examples/purchase_tester/android/app/src/main/AndroidManifest.xml
  revenuecat_examples/purchase_tester/android/app/src/main/java/com/revenuecat/purchases_sample/EmbeddingV1Activity.java
Labels: refactor

#869 `CI`: disable `prepare-next-version`
  .circleci/config.yml
  fastlane/Fastfile
Labels: ci

#872 Fix flutter analyze deprecation warnings
  lib/purchases_flutter.dart
Labels: refactor

#753 `Trusted Entitlements`: add support for setting `EntitlementVerificationMode` and getting verification result in `EntitlementInfos` and `EntitlementInfo`
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  api_tester/lib/api_tests/models/entitlement_info_wrapper_api_test.dart
  api_tester/lib/api_tests/models/entitlement_infos_wrapper_api_test.dart
  fastlane/README.md
  ios/Classes/PurchasesFlutterPlugin.m
  lib/models/entitlement_info_wrapper.dart
  lib/models/entitlement_info_wrapper.freezed.dart
  lib/models/entitlement_info_wrapper.g.dart
  lib/models/entitlement_infos_wrapper.dart
  lib/models/entitlement_infos_wrapper.freezed.dart
  lib/models/entitlement_infos_wrapper.g.dart
  lib/models/entitlement_verification_mode.dart
  lib/models/purchases_configuration.dart
  lib/models/verification_result.dart
  lib/object_wrappers.dart
  lib/purchases_flutter.dart
  revenuecat_examples/purchase_tester/android/app/src/main/AndroidManifest.xml
  revenuecat_examples/purchase_tester/integration_test/app_test.dart
  revenuecat_examples/purchase_tester/lib/main.dart
  test/entitlement_info_test.dart
  test/purchases_flutter_test.dart
Labels: feat
