Repository RevenueCat/purchases-flutter, pull requests merged in 2023-04, with the labels that each got.

#653 Release/5.0.0-alpha.1
  .version
  CHANGELOG-LATEST.md
  CHANGELOG.md
  VERSIONS.md
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  ios/Classes/PurchasesFlutterPlugin.m
  ios/purchases_flutter.podspec
  macos/purchases_flutter.podspec
  pubspec.yaml
  revenuecat_examples/purchase_tester/android/app/build.gradle
  test/purchases_flutter_test.dart
Labels: next_release

#656 [BC5] Apply `presentedOfferingID`, `offerPaymentMode`,add new `purchaseStoreProduct()`, deprecated `purchaseProduct()`
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  api_tester/lib/api_tests/models/pricing_phase_wrapper_api_test.dart
  api_tester/lib/api_tests/models/store_product_wrapper_api_test.dart
  api_tester/lib/api_tests/models/subscription_option_wrapper_api_test.dart
  api_tester/lib/api_tests/purchases_flutter_api_test.dart
  lib/models/pricing_phase_wrapper.dart
  lib/models/pricing_phase_wrapper.freezed.dart
  lib/models/pricing_phase_wrapper.g.dart
  lib/models/store_product_wrapper.dart
  lib/models/store_product_wrapper.freezed.dart
  lib/models/store_product_wrapper.g.dart
  lib/models/subscription_option_wrapper.dart
  lib/models/subscription_option_wrapper.freezed.dart
  lib/models/subscription_option_wrapper.g.dart
  lib/object_wrappers.dart
  lib/product_type.dart
  lib/purchases_flutter.dart
  migrations/v5-MIGRATION.md
  test/purchases_flutter_test.dart
Labels: feat

#655 [BC5] Rename `UpgradeInfo` to `ProductChangeInfo` and hide unsupported `ProrationMode`s
  analysis_options.yaml
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  api_tester/lib/api_tests/models/pricing_phase_wrapper_api_test.dart
  api_tester/lib/api_tests/models/store_product_wrapper_api_test.dart
  api_tester/lib/api_tests/models/subscription_option_wrapper_api_test.dart
  api_tester/lib/api_tests/purchases_flutter_api_test.dart
  lib/google_product_change.dart
  lib/models/pricing_phase_wrapper.dart
  lib/models/pricing_phase_wrapper.freezed.dart
  lib/models/pricing_phase_wrapper.g.dart
  lib/models/store_product_wrapper.dart
  lib/models/store_product_wrapper.freezed.dart
  lib/models/store_product_wrapper.g.dart
  lib/models/subscription_option_wrapper.dart
  lib/models/subscription_option_wrapper.freezed.dart
  lib/models/subscription_option_wrapper.g.dart
  lib/object_wrappers.dart
  lib/product_type.dart
  lib/purchases_flutter.dart
  lib/upgrade_info.dart
  migrations/v5-MIGRATION.md
  test/google_product_change_info_test.dart
  test/purchases_flutter_test.dart
Labels: breaking

#658 Update CircleCI Xcode version to 14.3.0 and update iOS runtime to 16.4
  .circleci/config.yml
Labels: ci

#660 Fix docs for purchaseSubscriptionOption
  api_tester/lib/api_tests/models/period_wrapper_api_test.dart
  lib/models/period_wrapper.dart
  lib/models/period_wrapper.freezed.dart
  lib/models/period_wrapper.g.dart
  lib/purchases_flutter.dart
  test/purchases_flutter_test.dart
Labels: docs

#666 [BC5] Update to PHC beta.6
  android/build.gradle
  api_tester/lib/api_tests/models/period_wrapper_api_test.dart
  api_tester/lib/api_tests/models/store_product_wrapper_api_test.dart
  api_tester/lib/api_tests/purchases_flutter_api_test.dart
  ios/purchases_flutter.podspec
  lib/models/introductory_price.dart
  lib/models/period_unit.dart
  lib/models/period_wrapper.dart
  lib/models/period_wrapper.freezed.dart
  lib/models/period_wrapper.g.dart
  lib/models/store_product_wrapper.dart
  lib/models/store_product_wrapper.freezed.dart
  lib/models/store_product_wrapper.g.dart
  lib/object_wrappers.dart
  lib/product_category.dart
  lib/purchases_flutter.dart
  macos/purchases_flutter.podspec
  migrations/v5-MIGRATION.md
  revenuecat_examples/purchase_tester/ios/RevenueCast_PurchaseTesterTypescriptConfiguration.storekit
  revenuecat_examples/purchase_tester/ios/Runner.xcodeproj/project.pbxproj
  revenuecat_examples/purchase_tester/lib/src/app.dart
  test/introductory_price_test.dart
  test/purchases_flutter_test.dart
Labels: breaking

#667 Release/5.0.0-beta.2
  .version
  CHANGELOG-LATEST.md
  CHANGELOG.md
  VERSIONS.md
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  ios/Classes/PurchasesFlutterPlugin.m
  macos/purchases_flutter.podspec
  pubspec.yaml
Labels: next_release

#669 Update fastlane-plugin-revenuecat version
  Gemfile.lock
  fastlane/Fastfile
Labels: ci

#671 [CF-1345] Upgrade Flutter CI image
  .circleci/config.yml
Labels: ci
