Repository RevenueCat/purchases-flutter, pull requests merged in 2023-01, with the labels that each got.

#563 remove stalebot in favor of SLAs in Zendesk
  .github/stale.yml
Labels: ci

#569 Adds missing params for better changelogs when bumping
  Gemfile.lock
  fastlane/Fastfile
  fastlane/README.md
Labels: ci

#573 Update Gemfile.lock
  Gemfile.lock
Labels: ci

#574 Remove web support from description in pub.dev
  pubspec.yaml
Labels: docs

#577 Add beginRefundRequest APIs for iOS 15+
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  api_tester/lib/api_tests/errors_api_test.dart
  api_tester/lib/api_tests/purchases_flutter_api_test.dart
  ios/Classes/PurchasesFlutterPlugin.m
  lib/errors.dart
  lib/purchases_flutter.dart
  revenuecat_examples/purchase_tester/lib/src/app.dart
  test/purchases_flutter_test.dart
Labels: feat

#579 Adds StoreProduct.susbcriptionPeriod
  api_tester/lib/api_tests/models/store_product_wrapper_api_test.dart
  api_tester/lib/api_tests/purchases_flutter_api_test.dart
  lib/models/store_product_wrapper.dart
  lib/models/store_product_wrapper.freezed.dart
  lib/models/store_product_wrapper.g.dart
  lib/purchases_flutter.dart
  test/purchases_flutter_test.dart
Labels: feat

#584 Fix integration tests
  .circleci/config.yml
Labels: fix

#590 `DEVELOPMENT.md`: added section on how to run tests
  DEVELOPMENT.md
Labels: docs

#585 Fix error code parsing from native layer
  api_tester/lib/api_tests/errors_api_test.dart
  lib/errors.dart
  test/purchases_flutter_test.dart
Labels: fix

#580 Add tests for sending customer info upon adding listener
  test/purchases_flutter_test.dart
Labels: test

#589 Added `Purchases.setLogLevel`
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  api_tester/lib/api_tests/purchases_flutter_api_test.dart
  ios/Classes/PurchasesFlutterPlugin.m
  lib/purchases_flutter.dart
  revenuecat_examples/MagicWeather/lib/src/views/home.dart
  revenuecat_examples/purchase_tester/lib/src/app.dart
Labels: feat

#598 Update danger, fastlane and fastlane plugin
  Gemfile.lock
Labels: ci
