Repository RevenueCat/purchases-flutter, pull requests merged in 2023-10, with the labels that each got.

#824 Fix freezed tests
  lib/models/customer_info_wrapper.freezed.dart
  lib/models/customer_info_wrapper.g.dart
  lib/models/entitlement_info_wrapper.freezed.dart
  lib/models/entitlement_info_wrapper.g.dart
  lib/models/entitlement_infos_wrapper.freezed.dart
  lib/models/entitlement_infos_wrapper.g.dart
  lib/models/introductory_price.freezed.dart
  lib/models/introductory_price.g.dart
  lib/models/offering_wrapper.freezed.dart
  lib/models/offering_wrapper.g.dart
  lib/models/offerings_wrapper.freezed.dart
  lib/models/offerings_wrapper.g.dart
  lib/models/package_wrapper.freezed.dart
  lib/models/package_wrapper.g.dart
  lib/models/period_wrapper.freezed.dart
  lib/models/period_wrapper.g.dart
  lib/models/price_wrapper.freezed.dart
  lib/models/price_wrapper.g.dart
  lib/models/pricing_phase_wrapper.freezed.dart
  lib/models/pricing_phase_wrapper.g.dart
  lib/models/promotional_offer.freezed.dart
  lib/models/promotional_offer.g.dart
  lib/models/store_product_discount.freezed.dart
  lib/models/store_product_discount.g.dart
  lib/models/store_product_wrapper.freezed.dart
  lib/models/store_product_wrapper.g.dart
  lib/models/store_transaction.freezed.dart
  lib/models/store_transaction.g.dart
  lib/models/subscription_option_wrapper.freezed.dart
  lib/models/subscription_option_wrapper.g.dart
Labels: test

#679 Fix MacOS integration tests on latest Flutter
  .circleci/config.yml
Labels: ci

#827 Remove hold/test job
  .circleci/config.yml
Labels: ci

#829 Bump Android min sdk version to 19
  android/build.gradle
Labels: breaking

#821 Temporarily remode DEFERRED proration mode in preparation for upgrade to Billing Client 6
  api_tester/lib/api_tests/purchases_flutter_api_test.dart
  lib/models/google_product_change.dart
  lib/models/upgrade_info.dart
Labels: breaking

#830 Add support for showing in-app messages
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  api_tester/lib/api_tests/purchases_flutter_api_test.dart
  ios/Classes/PurchasesFlutterPlugin.m
  lib/models/purchases_configuration.dart
  lib/purchases_flutter.dart
  revenuecat_examples/purchase_tester/lib/src/app.dart
  test/purchases_flutter_test.dart
Labels: breaking

#831 Release/6.0.0
  .version
  CHANGELOG-LATEST.md
  CHANGELOG.md
  VERSIONS.md
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  ios/Classes/PurchasesFlutterPlugin.m
  ios/purchases_flutter.podspec
  macos/purchases_flutter.podspec
  pubspec.yaml
  revenuecat_examples/purchase_tester/android/.project
  revenuecat_examples/purchase_tester/android/.settings/org.eclipse.buildship.core.prefs
  revenuecat_examples/purchase_tester/android/app/.project
Labels: next_release
