Repository RevenueCat/purchases-flutter, pull requests merged in 2024-02, with the labels that each got.

#960 [EXTERNAL] Adds productPlanIdentifier parameter to EntitlementInfo (#910) via @splangi
  api_tester/lib/api_tests/models/entitlement_info_wrapper_api_test.dart
  lib/models/entitlement_info_wrapper.dart
  lib/models/entitlement_info_wrapper.freezed.dart
  lib/models/entitlement_info_wrapper.g.dart
Labels: feat

#965 Bump PHC 6.3.1
  android/build.gradle
  ios/purchases_flutter.podspec
  macos/purchases_flutter.podspec
Labels: dependencies

#969 Fix freezed tests after latest freezed update
  lib/models/customer_info_wrapper.freezed.dart
  lib/models/entitlement_info_wrapper.freezed.dart
  lib/models/entitlement_infos_wrapper.freezed.dart
  lib/models/introductory_price.freezed.dart
  lib/models/offering_wrapper.freezed.dart
  lib/models/offerings_wrapper.freezed.dart
  lib/models/package_wrapper.freezed.dart
  lib/models/period_wrapper.freezed.dart
  lib/models/price_wrapper.freezed.dart
  lib/models/pricing_phase_wrapper.freezed.dart
  lib/models/promotional_offer.freezed.dart
  lib/models/store_product_discount.freezed.dart
  lib/models/store_product_wrapper.freezed.dart
  lib/models/store_transaction.freezed.dart
  lib/models/subscription_option_wrapper.freezed.dart
Labels: test

#985 Fix ios integration tests
  .circleci/config.yml
  revenuecat_examples/purchase_tester/integration_test/app_test.dart
Labels: test

#954 PaywallView support
  android/build.gradle
  api_tester/lib/api_tests/purchases_ui_flutter_api_test.dart
  purchases_ui_flutter/android/build.gradle
  purchases_ui_flutter/android/src/main/kotlin/com/revenuecat/purchases_ui_flutter/PurchasesUiFlutterPlugin.kt
  purchases_ui_flutter/android/src/main/kotlin/com/revenuecat/purchases_ui_flutter/views/PaywallView.kt
  purchases_ui_flutter/android/src/main/kotlin/com/revenuecat/purchases_ui_flutter/views/PaywallViewFactory.kt
  purchases_ui_flutter/ios/Classes/PurchasesUiFlutterPlugin.swift
  purchases_ui_flutter/ios/Classes/PurchasesUiPaywallView.swift
  purchases_ui_flutter/lib/purchases_ui_flutter.dart
  purchases_ui_flutter/lib/views/paywall_view.dart
  revenuecat_examples/purchase_tester/android/app/build.gradle
  revenuecat_examples/purchase_tester/android/build.gradle
  revenuecat_examples/purchase_tester/android/gradle/wrapper/gradle-wrapper.properties
  revenuecat_examples/purchase_tester/lib/src/paywall.dart
  revenuecat_examples/purchase_tester/lib/src/upsell.dart
Labels: feat, RevenueCatUI
