Repository RevenueCat/purchases-flutter, pull requests merged in 2024-01, with the labels that each got.

#917 Update PHC to latest paywall beta
  android/build.gradle
  ios/purchases_flutter.podspec
  macos/purchases_flutter.podspec
Labels: RevenueCatUI

#916 Remove result from presentPaywall methods
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  api_tester/lib/api_tests/purchases_flutter_api_test.dart
  lib/purchases_flutter.dart
  revenuecat_examples/purchase_tester/lib/src/app.dart
Labels: RevenueCatUI

#919 Create `purchases_flutter_ui` package
  .circleci/config.yml
  .pubignore
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  api_tester/lib/api_tests/purchases_flutter_api_test.dart
  api_tester/lib/api_tests/purchases_flutter_ui_api_test.dart
  api_tester/lib/api_tests_import.dart
  api_tester/pubspec.yaml
  fastlane/Fastfile
  fastlane/README.md
  ios/Classes/PurchasesFlutterPlugin.m
  lib/purchases_flutter.dart
  purchases_flutter_ui/.gitignore
  purchases_flutter_ui/.metadata
  purchases_flutter_ui/.pubignore
  purchases_flutter_ui/CHANGELOG.md
  purchases_flutter_ui/LICENSE
  purchases_flutter_ui/README.md
  purchases_flutter_ui/analysis_options.yaml
  purchases_flutter_ui/android/.gitignore
  purchases_flutter_ui/android/build.gradle
  purchases_flutter_ui/android/gradle/wrapper/gradle-wrapper.properties
  purchases_flutter_ui/android/settings.gradle
  purchases_flutter_ui/android/src/main/AndroidManifest.xml
  purchases_flutter_ui/android/src/main/kotlin/com/revenuecat/purchases_flutter_ui/PurchasesFlutterUiPlugin.kt
  purchases_flutter_ui/example/README.md
  purchases_flutter_ui/ios/.gitignore
  purchases_flutter_ui/ios/Assets/.gitkeep
  purchases_flutter_ui/ios/Classes/PurchasesFlutterUiPlugin.swift
  purchases_flutter_ui/ios/purchases_flutter_ui.podspec
  purchases_flutter_ui/lib/purchases_flutter_ui.dart
  purchases_flutter_ui/macos/Classes/PurchasesFlutterUiPlugin.swift
  purchases_flutter_ui/macos/purchases_flutter_ui.podspec
  purchases_flutter_ui/pubspec.yaml
  purchases_flutter_ui/test/purchases_flutter_ui_test.dart
  revenuecat_examples/purchase_tester/ios/Runner.xcodeproj/project.pbxproj
  revenuecat_examples/purchase_tester/lib/src/app.dart
  revenuecat_examples/purchase_tester/macos/Flutter/GeneratedPluginRegistrant.swift
  revenuecat_examples/purchase_tester/pubspec.yaml
  test/purchases_flutter_test.dart
Labels: RevenueCatUI

#923 Update `paywalls` to latest `main`
  CHANGELOG.md
  Gemfile.lock
  VERSIONS.md
Labels: RevenueCatUI

#924 Fix pub score for `purchases-ui-flutter`
  purchases_ui_flutter/lib/purchases_ui_flutter.dart
  purchases_ui_flutter/pubspec.yaml
  purchases_ui_flutter/test/purchases_ui_flutter_test.dart
Labels: RevenueCatUI

#925 Release/6.15.0-beta.4
  .version
  CHANGELOG-LATEST.md
  CHANGELOG.md
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  ios/Classes/PurchasesFlutterPlugin.m
  ios/purchases_flutter.podspec
  macos/purchases_flutter.podspec
  pubspec.yaml
  purchases_ui_flutter/android/build.gradle
  purchases_ui_flutter/ios/purchases_ui_flutter.podspec
  purchases_ui_flutter/macos/purchases_ui_flutter.podspec
  purchases_ui_flutter/pubspec.yaml
Labels: next_release

#927 Fix github_release job not running after release jobs
  .circleci/config.yml
Labels: ci

#926 Add result to presentPaywall methods
  android/build.gradle
  api_tester/lib/api_tests/purchases_ui_flutter_api_test.dart
  ios/purchases_flutter.podspec
  macos/purchases_flutter.podspec
  purchases_ui_flutter/android/build.gradle
  purchases_ui_flutter/android/src/main/kotlin/com/revenuecat/purchases_ui_flutter/PurchasesUiFlutterPlugin.kt
  purchases_ui_flutter/ios/Classes/PurchasesUiFlutterPlugin.swift
  purchases_ui_flutter/ios/purchases_ui_flutter.podspec
  purchases_ui_flutter/lib/paywall_result.dart
  purchases_ui_flutter/lib/purchases_ui_flutter.dart
  purchases_ui_flutter/macos/purchases_ui_flutter.podspec
  purchases_ui_flutter/test/purchases_ui_flutter_test.dart
  revenuecat_examples/purchase_tester/lib/src/app.dart
Labels: RevenueCatUI

#933 Update `fastlane-plugin-revenuecat_internal`
  Gemfile.lock
Labels: ci

#932 Release/6.15.0
  .version
  CHANGELOG-LATEST.md
  CHANGELOG.md
  VERSIONS.md
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  ios/Classes/PurchasesFlutterPlugin.m
  ios/purchases_flutter.podspec
  macos/purchases_flutter.podspec
  pubspec.yaml
  purchases_ui_flutter/android/build.gradle
  purchases_ui_flutter/ios/purchases_ui_flutter.podspec
  purchases_ui_flutter/macos/purchases_ui_flutter.podspec
  purchases_ui_flutter/pubspec.yaml
Labels: next_release

#943 `Paywalls`: separate `PurchasesHybridCommonUI`
  android/build.gradle
  fastlane/Fastfile
  ios/purchases_flutter.podspec
  macos/purchases_flutter.podspec
  purchases_ui_flutter/android/build.gradle
  purchases_ui_flutter/ios/Classes/PurchasesUiFlutterPlugin.swift
  purchases_ui_flutter/ios/purchases_ui_flutter.podspec
  purchases_ui_flutter/macos/purchases_ui_flutter.podspec
  revenuecat_examples/purchase_tester/ios/Runner.xcodeproj/project.pbxproj
Labels: perf, RevenueCatUI

#950 Refactor and cleanup of purchase_tester
  revenuecat_examples/purchase_tester/lib/src/app.dart
  revenuecat_examples/purchase_tester/lib/src/cats.dart
  revenuecat_examples/purchase_tester/lib/src/initial.dart
  revenuecat_examples/purchase_tester/lib/src/upsell.dart
Labels: refactor

#947 `Paywalls`: added `Offering` parameter to `presentPaywall` methods
  .circleci/config.yml
  api_tester/lib/api_tests/purchases_ui_flutter_api_test.dart
  api_tester/pubspec.yaml
  fastlane/Fastfile
  purchases_ui_flutter/android/src/main/kotlin/com/revenuecat/purchases_ui_flutter/PurchasesUiFlutterPlugin.kt
  purchases_ui_flutter/ios/Classes/PurchasesUiFlutterPlugin.swift
  purchases_ui_flutter/lib/purchases_ui_flutter.dart
  purchases_ui_flutter/pubspec.yaml
  purchases_ui_flutter/test/purchases_ui_flutter_test.dart
  revenuecat_examples/purchase_tester/pubspec.yaml
Labels: RevenueCatUI

#948 `Paywalls`: `displayCloseButton` parameter
  api_tester/lib/api_tests/purchases_ui_flutter_api_test.dart
  purchases_ui_flutter/android/src/main/kotlin/com/revenuecat/purchases_ui_flutter/PurchasesUiFlutterPlugin.kt
  purchases_ui_flutter/ios/Classes/PurchasesUiFlutterPlugin.swift
  purchases_ui_flutter/lib/purchases_ui_flutter.dart
  purchases_ui_flutter/test/purchases_ui_flutter_test.dart
Labels: RevenueCatUI
