Repository RevenueCat/purchases-flutter, pull requests merged in 2024-08, with the labels that each got.

#1129 v7.0.0
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  api_tester/lib/api_tests/models/installments_info_api_test.dart
  api_tester/lib/api_tests/models/purchase_configuration_api_test.dart
  api_tester/lib/api_tests/models/subscription_option_wrapper_api_test.dart
  api_tester/lib/api_tests/purchases_flutter_api_test.dart
  api_tester/lib/api_tests_import.dart
  ios/Classes/PurchasesFlutterPlugin.m
  ios/purchases_flutter.podspec
  lib/models/google_product_change.dart
  lib/models/installments_info.dart
  lib/models/installments_info.freezed.dart
  lib/models/installments_info.g.dart
  lib/models/purchases_completed_by.dart
  lib/models/purchases_configuration.dart
  lib/models/storekit_version.dart
  lib/models/subscription_option_wrapper.dart
  lib/models/subscription_option_wrapper.freezed.dart
  lib/models/subscription_option_wrapper.g.dart
  lib/models/upgrade_info.dart
  lib/object_wrappers.dart
  lib/purchases_flutter.dart
  macos/purchases_flutter.podspec
  migrations/v7-MIGRATION.md
  purchases_ui_flutter/android/build.gradle
  purchases_ui_flutter/ios/purchases_ui_flutter.podspec
  purchases_ui_flutter/macos/purchases_ui_flutter.podspec
  revenuecat_examples/MagicWeather/ios/Podfile
  revenuecat_examples/MagicWeather/ios/Runner.xcodeproj/project.pbxproj
  revenuecat_examples/MagicWeather/lib/main.dart
  revenuecat_examples/purchase_tester/ios/Podfile
  revenuecat_examples/purchase_tester/ios/Runner.xcodeproj/project.pbxproj
  revenuecat_examples/purchase_tester/lib/main.dart
  revenuecat_examples/purchase_tester/macos/Podfile
  revenuecat_examples/purchase_tester/macos/Runner.xcodeproj/project.pbxproj
  test/purchases_flutter_test.dart
Labels: feat

#1130 Release/7.0.0
  .version
  CHANGELOG-LATEST.md
  CHANGELOG.md
  VERSIONS.md
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  ios/Classes/PurchasesFlutterPlugin.m
  ios/purchases_flutter.podspec
  macos/purchases_flutter.podspec
  pubspec.yaml
  purchases_ui_flutter/android/build.gradle
  purchases_ui_flutter/ios/purchases_ui_flutter.podspec
  purchases_ui_flutter/macos/purchases_ui_flutter.podspec
  purchases_ui_flutter/pubspec.yaml
Labels: next_release

#1132 update purchases_flutter dependency to 7.0.0 on purchases_ui_flutter
  .circleci/config.yml
  fastlane/Fastfile
  lib/models/customer_info_wrapper.freezed.dart
  lib/models/entitlement_info_wrapper.freezed.dart
  lib/models/entitlement_infos_wrapper.freezed.dart
  lib/models/installments_info.freezed.dart
  lib/models/introductory_price.freezed.dart
  lib/models/offering_wrapper.freezed.dart
  lib/models/offerings_wrapper.freezed.dart
  lib/models/package_wrapper.freezed.dart
  lib/models/period_wrapper.freezed.dart
  lib/models/presented_offering_context_wrapper.freezed.dart
  lib/models/presented_offering_targeting_context_wrapper.freezed.dart
  lib/models/price_wrapper.freezed.dart
  lib/models/pricing_phase_wrapper.freezed.dart
  lib/models/promotional_offer.freezed.dart
  lib/models/purchases_error.freezed.dart
  lib/models/store_product_discount.freezed.dart
  lib/models/store_product_wrapper.freezed.dart
  lib/models/store_transaction.freezed.dart
  lib/models/subscription_option_wrapper.freezed.dart
  purchases_ui_flutter/pubspec.yaml
Labels: fix

#1133 Update fastlane-plugin-revenuecat_internal
  Gemfile.lock
Labels: fix

#1134 Release/7.0.1
  .version
  CHANGELOG-LATEST.md
  CHANGELOG.md
  VERSIONS.md
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  ios/Classes/PurchasesFlutterPlugin.m
  ios/purchases_flutter.podspec
  macos/purchases_flutter.podspec
  pubspec.yaml
  purchases_ui_flutter/android/build.gradle
  purchases_ui_flutter/ios/purchases_ui_flutter.podspec
  purchases_ui_flutter/macos/purchases_ui_flutter.podspec
  purchases_ui_flutter/pubspec.yaml
Labels: next_release

#1137 Update iOS deployment target in readme
  README.md
Labels: docs

#1138 Parse recordPurchase response
  lib/purchases_flutter.dart
Labels: fix

#1144 v7-MIGRATION.md typo fix
  migrations/v7-MIGRATION.md
Labels: docs

#1143 Refine StoreKitVersion logging in configure function
  lib/purchases_flutter.dart
Labels: fix

#1141 Remove embedding v1 support
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
Labels: breaking

#1147 Fix purchases-ui-flutter main SDK version substitution
  fastlane/Fastfile
Labels: ci
