Repository RevenueCat/purchases-flutter, pull requests merged in 2024-03, with the labels that each got.

#996 `PaywallFooterView` support
  purchases_ui_flutter/android/src/main/kotlin/com/revenuecat/purchases_ui_flutter/PurchasesUiFlutterPlugin.kt
  purchases_ui_flutter/android/src/main/kotlin/com/revenuecat/purchases_ui_flutter/views/PaywallFooterView.kt
  purchases_ui_flutter/android/src/main/kotlin/com/revenuecat/purchases_ui_flutter/views/PaywallFooterViewFactory.kt
  purchases_ui_flutter/android/src/main/kotlin/com/revenuecat/purchases_ui_flutter/views/PaywallView.kt
  purchases_ui_flutter/ios/Classes/PurchasesUiFlutterPlugin.swift
  purchases_ui_flutter/ios/Classes/PurchasesUiPaywallFooterView.swift
  purchases_ui_flutter/lib/purchases_ui_flutter.dart
  purchases_ui_flutter/lib/views/internal_paywall_footer_view.dart
  purchases_ui_flutter/lib/views/paywall_footer_view.dart
  revenuecat_examples/purchase_tester/lib/src/paywall_footer_screen.dart
  revenuecat_examples/purchase_tester/lib/src/upsell.dart
Labels: feat

#1001 Change iOS platform version of purchase_tester
  revenuecat_examples/purchase_tester/ios/Flutter/AppFrameworkInfo.plist
  revenuecat_examples/purchase_tester/ios/Podfile
  revenuecat_examples/purchase_tester/ios/Runner.xcodeproj/project.pbxproj
  revenuecat_examples/purchase_tester/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
Labels: build

#1007 Add dependency_overrides to purchases_flutter_ui
  fastlane/Fastfile
  purchases_ui_flutter/pubspec.yaml
Labels: build

#995 Add `PaywallView` listeners
  api_tester/lib/api_tests/models/purchases_error_api_test.dart
  api_tester/lib/api_tests/purchases_ui_flutter_api_test.dart
  api_tester/lib/api_tests_import.dart
  lib/models/purchases_error.dart
  lib/models/purchases_error.freezed.dart
  lib/models/purchases_error.g.dart
  lib/object_wrappers.dart
  purchases_ui_flutter/android/src/main/kotlin/com/revenuecat/purchases_ui_flutter/PurchasesUiFlutterPlugin.kt
  purchases_ui_flutter/android/src/main/kotlin/com/revenuecat/purchases_ui_flutter/views/PaywallView.kt
  purchases_ui_flutter/android/src/main/kotlin/com/revenuecat/purchases_ui_flutter/views/PaywallViewFactory.kt
  purchases_ui_flutter/ios/Classes/PurchasesUiPaywallView.swift
  purchases_ui_flutter/ios/Classes/UnsupportedPlatformView.swift
  purchases_ui_flutter/lib/views/paywall_view.dart
  revenuecat_examples/purchase_tester/lib/src/paywall.dart
Labels: feat

#1011 Add 5.8.2 to changelog
  CHANGELOG.md
  VERSIONS.md
Labels: docs

#1014 Adds`Purchases.getCurrentOfferingForPlacement(placementID)` and `Purchases.syncAttributesAndOfferingsIfNeeded()`
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  api_tester/lib/api_tests/models/package_wrapper_api_test.dart
  api_tester/lib/api_tests/models/store_product_wrapper_api_test.dart
  api_tester/lib/api_tests/models/subscription_option_wrapper_api_test.dart
  api_tester/lib/api_tests/purchases_flutter_api_test.dart
  ios/Classes/PurchasesFlutterPlugin.m
  lib/models/package_wrapper.dart
  lib/models/package_wrapper.freezed.dart
  lib/models/package_wrapper.g.dart
  lib/models/presented_offering_context_wrapper.dart
  lib/models/presented_offering_context_wrapper.freezed.dart
  lib/models/presented_offering_context_wrapper.g.dart
  lib/models/presented_offering_targeting_context_wrapper.dart
  lib/models/presented_offering_targeting_context_wrapper.freezed.dart
  lib/models/presented_offering_targeting_context_wrapper.g.dart
  lib/models/store_product_wrapper.dart
  lib/models/store_product_wrapper.freezed.dart
  lib/models/store_product_wrapper.g.dart
  lib/models/subscription_option_wrapper.dart
  lib/models/subscription_option_wrapper.freezed.dart
  lib/models/subscription_option_wrapper.g.dart
  lib/object_wrappers.dart
  lib/purchases_flutter.dart
  revenuecat_examples/purchase_tester/lib/src/upsell.dart
  test/offering_test.dart
  test/purchases_flutter_test.dart
Labels: breaking

#1018 Fix footer sizing issues in iOS
  purchases_ui_flutter/ios/Classes/PurchasesUiPaywallFooterView.swift
  purchases_ui_flutter/lib/views/paywall_footer_view.dart
Labels: fix

#1012 Add `PaywallFooterView` listeners
  api_tester/lib/api_tests/purchases_ui_flutter_api_test.dart
  purchases_ui_flutter/android/src/main/kotlin/com/revenuecat/purchases_ui_flutter/views/PaywallFooterView.kt
  purchases_ui_flutter/ios/Classes/PurchasesUiPaywallFooterView.swift
  purchases_ui_flutter/ios/Classes/PurchasesUiPaywallView.swift
  purchases_ui_flutter/lib/views/internal_paywall_footer_view.dart
  purchases_ui_flutter/lib/views/paywall_footer_view.dart
  purchases_ui_flutter/lib/views/paywall_view.dart
  purchases_ui_flutter/lib/views/paywall_view_method_handler.dart
  revenuecat_examples/purchase_tester/lib/src/paywall_footer_screen.dart
Labels: feat

#1009 Add `onDismiss` handler and `displayCloseButton` to `PaywallView` and `PaywallFooterView`
  api_tester/lib/api_tests/purchases_ui_flutter_api_test.dart
  purchases_ui_flutter/android/src/main/kotlin/com/revenuecat/purchases_ui_flutter/views/PaywallFooterView.kt
  purchases_ui_flutter/android/src/main/kotlin/com/revenuecat/purchases_ui_flutter/views/PaywallView.kt
  purchases_ui_flutter/ios/Classes/PurchasesUiPaywallFooterView.swift
  purchases_ui_flutter/ios/Classes/PurchasesUiPaywallView.swift
  purchases_ui_flutter/lib/views/internal_paywall_footer_view.dart
  purchases_ui_flutter/lib/views/paywall_footer_view.dart
  purchases_ui_flutter/lib/views/paywall_view.dart
  purchases_ui_flutter/lib/views/paywall_view_method_handler.dart
  revenuecat_examples/purchase_tester/lib/src/paywall.dart
  revenuecat_examples/purchase_tester/lib/src/paywall_footer_screen.dart
Labels: feat

#1029 Add `RC_BILLING` store
  api_tester/lib/api_tests/models/store_api_test.dart
  lib/models/entitlement_info_wrapper.g.dart
  lib/models/store.dart
Labels: HOLD, refactor
