Repository RevenueCat/purchases-flutter, pull requests merged in 2024-10, with the labels that each got.

#1176 Update fastlane plugin
  Gemfile.lock
Labels: pr:other

#1179 Fix area insets in PaywallView
  purchases_ui_flutter/ios/Classes/PurchasesUiPaywallView.swift
Labels: pr:fix, pr:RevenueCatUI

#1194 Support displaying deferred win-back StoreKit messages
  api_tester/lib/api_tests/purchases_flutter_api_test.dart
  lib/purchases_flutter.dart
Labels: pr:feat, feat:Win-Back Offers
