Repository RevenueCat/purchases-flutter, pull requests merged in 2025-09, with the labels that each got.

#1443 Virtual Currency Support for Flutter Web
  lib/web/purchases_flutter_web.dart
  revenuecat_examples/purchase_tester/lib/src/virtual_currency_testing_screen.dart
Labels: pr:feat

#1452 Support integration via Swift Package Manager
  .circleci/config.yml
  .gitignore
  fastlane/Fastfile
  ios/purchases_flutter.podspec
  ios/purchases_flutter/Package.swift
  ios/purchases_flutter/Sources/purchases_flutter/Assets/.gitkeep
  ios/purchases_flutter/Sources/purchases_flutter/PurchasesFlutterPlugin.m
  ios/purchases_flutter/Sources/purchases_flutter/include/purchases_flutter/PurchasesFlutterPlugin.h
  macos/Classes/PurchasesFlutterPlugin.h
  macos/Classes/PurchasesFlutterPlugin.m
  macos/purchases_flutter.podspec
  macos/purchases_flutter/Package.swift
  macos/purchases_flutter/Sources/purchases_flutter/PurchasesFlutterPlugin.m
  macos/purchases_flutter/Sources/purchases_flutter/include/purchases_flutter/PurchasesFlutterPlugin.h
  purchases_ui_flutter/ios/purchases_ui_flutter.podspec
  purchases_ui_flutter/ios/purchases_ui_flutter/Package.swift
  purchases_ui_flutter/ios/purchases_ui_flutter/Sources/purchases_ui_flutter/Assets/.gitkeep
  purchases_ui_flutter/ios/purchases_ui_flutter/Sources/purchases_ui_flutter/Helpers/UIView+Extensions.swift
  purchases_ui_flutter/ios/purchases_ui_flutter/Sources/purchases_ui_flutter/Helpers/ViewControllerWrapper.swift
  purchases_ui_flutter/ios/purchases_ui_flutter/Sources/purchases_ui_flutter/PurchasesUiFlutterPlugin.swift
  purchases_ui_flutter/ios/purchases_ui_flutter/Sources/purchases_ui_flutter/PurchasesUiPaywallFooterView.swift
  purchases_ui_flutter/ios/purchases_ui_flutter/Sources/purchases_ui_flutter/PurchasesUiPaywallView.swift
  purchases_ui_flutter/ios/purchases_ui_flutter/Sources/purchases_ui_flutter/UnsupportedPlatformView.swift
  purchases_ui_flutter/macos/Classes/PurchasesUiFlutterPlugin.swift
  purchases_ui_flutter/macos/purchases_ui_flutter.podspec
  purchases_ui_flutter/macos/purchases_ui_flutter/Package.swift
  purchases_ui_flutter/macos/purchases_ui_flutter/Sources/purchases_ui_flutter/PurchasesUiFlutterPlugin.swift
Labels: pr:feat

#1454 Default to Swift Package Manager in Purchase Tester (instead of CocoaPods)
  revenuecat_examples/purchase_tester/ios/Flutter/AppFrameworkInfo.plist
  revenuecat_examples/purchase_tester/ios/Flutter/Debug.xcconfig
  revenuecat_examples/purchase_tester/ios/Flutter/Release.xcconfig
  revenuecat_examples/purchase_tester/ios/Podfile
  revenuecat_examples/purchase_tester/ios/Runner.xcodeproj/project.pbxproj
  revenuecat_examples/purchase_tester/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  revenuecat_examples/purchase_tester/ios/Runner.xcworkspace/contents.xcworkspacedata
  revenuecat_examples/purchase_tester/ios/RunnerTests/RunnerTests.swift
  revenuecat_examples/purchase_tester/macos/Flutter/Flutter-Debug.xcconfig
  revenuecat_examples/purchase_tester/macos/Flutter/Flutter-Release.xcconfig
  revenuecat_examples/purchase_tester/macos/Flutter/GeneratedPluginRegistrant.swift
  revenuecat_examples/purchase_tester/macos/Podfile
  revenuecat_examples/purchase_tester/macos/Runner.xcodeproj/project.pbxproj
  revenuecat_examples/purchase_tester/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  revenuecat_examples/purchase_tester/macos/Runner.xcworkspace/contents.xcworkspacedata
  revenuecat_examples/purchase_tester/macos/Runner/AppDelegate.swift
  revenuecat_examples/purchase_tester/macos/RunnerTests/RunnerTests.swift
Labels: pr:other

#1472 Fix crash when calling new purchase w/ purchase params function
  ios/purchases_flutter/Sources/purchases_flutter/PurchasesFlutterPlugin.m
Labels: pr:fix

#1489 Add CODEOWNERS
  .github/CODEOWNERS
Labels: pr:other
