Repository RevenueCat/purchases-flutter, pull requests merged in 2025-04, with the labels that each got.

#1304 Add Virtual Currency Balances
  api_tester/lib/api_tests/models/customer_info_wrapper_api_test.dart
  api_tester/lib/api_tests/purchases_flutter_api_test.dart
  lib/models/customer_info_wrapper.dart
  lib/models/customer_info_wrapper.freezed.dart
  lib/models/customer_info_wrapper.g.dart
  lib/models/virtual_currency_info.dart
  lib/models/virtual_currency_info.freezed.dart
  lib/models/virtual_currency_info.g.dart
  lib/object_wrappers.dart
  test/purchases_flutter_test.dart
  test/virtual_currency_info_test.dart
  test/web_purchase_redemption_result_test.dart
Labels: pr:feat

#1327 Reverts version bumps done in f21e068
  pubspec.yaml
Labels: pr:fix

#1328 Bump min supported versions and add tests for min SDK compatibility
  .circleci/config.yml
  pubspec.yaml
  purchases_ui_flutter/pubspec.yaml
Labels: pr:other

#1237 [Beta] Flutter Web support
  .circleci/config.yml
  fastlane/Fastfile
  lib/models/google_product_change.dart
  lib/purchases_flutter.dart
  lib/web/purchases_flutter_web.dart
  pubspec.yaml
  purchases_ui_flutter/pubspec.yaml
  revenuecat_examples/MagicWeather/.metadata
  revenuecat_examples/MagicWeather/ios/Runner.xcodeproj/project.pbxproj
  revenuecat_examples/MagicWeather/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  revenuecat_examples/MagicWeather/ios/Runner/AppDelegate.swift
  revenuecat_examples/MagicWeather/ios/Runner/Info.plist
  revenuecat_examples/MagicWeather/lib/main.dart
  revenuecat_examples/MagicWeather/lib/src/components/native_dialog.dart
  revenuecat_examples/MagicWeather/lib/src/components/top_bar.dart
  revenuecat_examples/MagicWeather/lib/src/constant.dart
  revenuecat_examples/MagicWeather/lib/store_config.dart
  revenuecat_examples/MagicWeather/pubspec.yaml
  revenuecat_examples/MagicWeather/web/favicon.png
  revenuecat_examples/MagicWeather/web/icons/Icon-192.png
  revenuecat_examples/MagicWeather/web/icons/Icon-512.png
  revenuecat_examples/MagicWeather/web/icons/Icon-maskable-192.png
  revenuecat_examples/MagicWeather/web/icons/Icon-maskable-512.png
  revenuecat_examples/MagicWeather/web/index.html
  revenuecat_examples/MagicWeather/web/manifest.json
  revenuecat_examples/purchase_tester/.metadata
  revenuecat_examples/purchase_tester/lib/main.dart
  revenuecat_examples/purchase_tester/lib/src/constant.dart
  revenuecat_examples/purchase_tester/lib/src/upsell.dart
  revenuecat_examples/purchase_tester/pubspec.yaml
  revenuecat_examples/purchase_tester/web/favicon.png
  revenuecat_examples/purchase_tester/web/icons/Icon-192.png
  revenuecat_examples/purchase_tester/web/icons/Icon-512.png
  revenuecat_examples/purchase_tester/web/icons/Icon-maskable-192.png
  revenuecat_examples/purchase_tester/web/icons/Icon-maskable-512.png
  revenuecat_examples/purchase_tester/web/index.html
  revenuecat_examples/purchase_tester/web/manifest.json
Labels: pr:breaking, pr:feat
