Repository RevenueCat/purchases-flutter, pull requests merged in 2025-02, with the labels that each got.

#1263 Fix flutter doctor issue
  .circleci/config.yml
Labels: pr:other

#1256 [Paywalls V2] Deprecate PaywallFooterView in favor of OriginalTemplatePaywallFooterView
  api_tester/lib/api_tests/purchases_ui_flutter_api_test.dart
  purchases_ui_flutter/lib/purchases_ui_flutter.dart
  purchases_ui_flutter/lib/views/paywall_footer_view.dart
  purchases_ui_flutter/lib/views/paywall_view.dart
  revenuecat_examples/purchase_tester/lib/src/paywall_footer_screen.dart
Labels: pr:RevenueCatUI, pr:other

#1270 Add proguard-rules.pro to `purchases-ui-flutter`
  purchases_ui_flutter/android/build.gradle
  purchases_ui_flutter/android/proguard-rules.pro
Labels: pr:fix

#1274 chore: Update proguard-rules.pro like flutter_ui
  android/proguard-rules.pro
  purchases_ui_flutter/android/build.gradle
  purchases_ui_flutter/android/proguard-rules.pro
Labels: enhancement, pr:other

#1277 Add prepaid periodType
  api_tester/lib/api_tests/models/entitlement_info_wrapper_api_test.dart
  lib/models/entitlement_info_wrapper.dart
  lib/models/entitlement_info_wrapper.g.dart
  test/entitlement_info_test.dart
Labels: bug, pr:fix

#1261 feat: Introduce CustomerCenter
  .gitignore
  api_tester/lib/api_tests/purchases_ui_flutter_api_test.dart
  purchases_ui_flutter/android/src/main/kotlin/com/revenuecat/purchases_ui_flutter/PurchasesUiFlutterPlugin.kt
  purchases_ui_flutter/android/src/main/kotlin/com/revenuecat/purchases_ui_flutter/views/PaywallFooterView.kt
  purchases_ui_flutter/android/src/main/kotlin/com/revenuecat/purchases_ui_flutter/views/PaywallView.kt
  purchases_ui_flutter/ios/Classes/Helpers/UIView+Extensions.swift
  purchases_ui_flutter/ios/Classes/Helpers/ViewControllerWrapper.swift
  purchases_ui_flutter/ios/Classes/PurchasesUiFlutterPlugin.swift
  purchases_ui_flutter/ios/Classes/PurchasesUiPaywallView.swift
  purchases_ui_flutter/lib/purchases_ui_flutter.dart
  revenuecat_examples/purchase_tester/lib/src/upsell.dart
Labels: pr:feat, pr:RevenueCatUI, feat:Customer Center
