Repository RevenueCat/purchases-flutter, pull requests merged in 2025-07, with the labels that each got.

#1387 Update workflows/issue-notifications.yml@v2
  .github/workflows/issue-notifications.yml
Labels: pr:other

#1408 Change result of purchase methods to PurchaseResult
  api_tester/lib/api_tests/models/purchase_result_api_test.dart
  api_tester/lib/api_tests/purchases_flutter_api_test.dart
  api_tester/lib/api_tests_import.dart
  lib/models/purchase_result.dart
  lib/object_wrappers.dart
  lib/purchases_flutter.dart
  lib/web/purchases_flutter_web.dart
  revenuecat_examples/MagicWeather/lib/src/views/paywall.dart
  revenuecat_examples/purchase_tester/lib/src/upsell.dart
  test/purchases_flutter_test.dart
Labels: pr:breaking, pr:feat

#1411 Fix wrong SDK version on web for analytics
  lib/web/purchases_flutter_web.dart
Labels: pr:other, pr:force_patch

#1416 [iOS + Android] Virtual Currency Support
  android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java
  api_tester/lib/api_tests/models/virtual_currencies_api_test.dart
  api_tester/lib/api_tests/models/virtual_currency_api_test.dart
  api_tester/lib/api_tests/purchases_flutter_api_test.dart
  api_tester/lib/api_tests_import.dart
  ios/Classes/PurchasesFlutterPlugin.m
  lib/models/virtual_currencies.dart
  lib/models/virtual_currency.dart
  lib/object_wrappers.dart
  lib/purchases_flutter.dart
  lib/web/purchases_flutter_web.dart
  revenuecat_examples/purchase_tester/lib/src/upsell.dart
  revenuecat_examples/purchase_tester/lib/src/virtual_currency_testing_screen.dart
  test/models/virtual_currencies_test.dart
  test/models/virtual_currency_test.dart
  test/purchases_flutter_test.dart
Labels: pr:feat

#1413 Support `setAttributes/setEmail/setDisplayName/setPhoneNumber` in Flutter Web
  lib/web/purchases_flutter_web.dart
Labels: pr:feat
